### ISSUE TITLE
zipcelx_1.default is not a function

### ISSUE THREAD

**Issue by BearandYoon** [egeriis/zipcelx#35]
Hello

I am using zipcelx package in my Angular 5 project and It has worked in version 1.2.0 very well.
I updated this package version from 1.2.0 to 1.4.0 using ncu(npm-check-updates) then from update the version, it doesn't work for me.

This is an error message.
```
zipcelx_1.default is not a function
```

This is my code snippet.
```
import zipcelx from 'zipcelx';
...
    const config = {
      filename: excelFileName,
      sheet: {
        data: otherData
      }
    };
    zipcelx(config); /// here error
```

this is a yarn lock info.
```
zipcelx@^1.4.0:
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/zipcelx/-/zipcelx-1.4.0.tgz#55055f49385ca11f35a397430992aef85b8cb9ea"
  dependencies:
    file-saver "^1.3.3"
    jszip "^3.1.3"
    lodash.escape "^4.0.1"
```

**Comment by egeriis** [comment]
Yeah, this is a known issue. I messed up the build in #20 🙂 Hoping to fix this weekend

**Comment by egeriis** [comment]
Duplicate of #31
